### ISSUE TITLE
Dark Theme on Mac

### ISSUE THREAD

**Issue by joeking9292** [osu-acm/website#12]
There is a problem with the CSS when opened on a Mac using dark theme

**Comment by laurajjiang** [comment]
<img width="1680" alt="Screen Shot 2019-10-15 at 12 05 57 PM" src="https://user-images.githubusercontent.com/39676345/66861615-322aef80-ef44-11e9-9688-b2e0efa6dccb.png">

**Comment by joeking9292** [comment]
Issue no longer relevant. New website is deployed
